### ISSUE TITLE
the loss of train the Syncnet is not going down

### ISSUE THREAD

**Issue by shz0519** [joonson/syncnet_python#15]
Hello,Thank you for the excellent work and publicly available code.
I'm trying to use the mvlrs_v1 datasets to train the Syncnet,but the loss keep oscillating:
![1](https://user-images.githubusercontent.com/16603261/62352953-09e24600-b53c-11e9-9c66-976187bad5ae.png)
![2](https://user-images.githubusercontent.com/16603261/62352973-19618f00-b53c-11e9-952c-0ab820cdabee.png)

Since  most video in the mvlrs_v1  is short,I randomly shift the audio up to 10-frame in order to generate synthetic false audio-video pairs.
1、Which datasets are you using?LRW/LRS2/LRS3?
2、Does the false pairs have to be shifted by up to 2s?
3、Can you show me your training log?
thank you!

**Comment by lijuntang** [comment]
shz0519, can you share your code fragment for training?

**Comment by prajwalkr** [comment]
Hello,

Were you able to solve this issue? I am facing a similar problem.

**Comment by joonson** [comment]
You can train the model using https://github.com/joonson/syncnet_trainer. Setting `alphaI=0` will make it train the lip sync-only model.
