### ISSUE TITLE
is RGB or BGR format used for the model

### ISSUE THREAD

**Issue by mpc001** [joonson/syncnet_python#16]
hi, thanks for your brilliant work! I am confused at two points:

1) do you use RGB or BGR as inputs for the model
https://github.com/joonson/syncnet_python/blob/a8a396a36c33cef659109864eb60af44fca900ef/SyncNetInstance.py#L52-L58
https://github.com/joonson/syncnet_python/blob/a8a396a36c33cef659109864eb60af44fca900ef/SyncNetInstance.py#L152-L159

2) are there any differences between these two steps? What I guess is 4...
https://github.com/joonson/syncnet_python/blob/a8a396a36c33cef659109864eb60af44fca900ef/SyncNetInstance.py#L94
https://github.com/joonson/syncnet_python/blob/a8a396a36c33cef659109864eb60af44fca900ef/SyncNetInstance.py#L171

thanks in advance!

**Comment by joonson** [comment]
This has been fixed.
