### ISSUE TITLE
python2 Vs python3

### ISSUE THREAD

**Issue by DavidDoukhan** [joonson/syncnet_python#19]
Dear @joonson ,

First of all I'd like to thank you for this software that is quite impressive!

I managed to run your code with python3 without any problems.

However, when I first rode the instructions found in the README.md , you suggested to use python 2.7 .
I tried to launch your program using python 2.7, but I faced few problems:
In scripts run_syncnet.py and run_visualise.py , you call function pickle.load with 2 arguments: the name of the pickled file AND an "encoding" named argument.
The "encoding" named argument is only supported in Python 3.
When I removed this encoding argument from the 2 scripts, the code worked fine.

So here are my suggestions:
* you could either tell in README.md that your program requires python3 instead of python2
* otherwise, you could change run_syncnet.py and run_visualise.py in order to remove the encoding argument used in pickle.load , that would allow the code to be run using python2

**Comment by joonson** [comment]
The code has been updated to use Python 3. Thanks for the suggestion.
