### ISSUE TITLE
adding requirements.txt

### ISSUE THREAD

**Issue by DavidDoukhan** [joonson/syncnet_python#20]
Dear @joonson ,

While trying to use your software, I wasted few hours trying to install the dependencies required by your program using several strategies: conda, pip, etc...

Then, I found a requirements.txt file in a fork of your repository, that allowed me to install easily all ther required software dependencies:
Here is the link to the file that worked for me, realized by @KeithlMyers :
https://github.com/KeithIMyers/syncnet_python/blob/master/requirements.txt

I would suggest to add this file to your repository, and update the README.md according to this new ressource.

Kind regards,

**Comment by joonson** [comment]
Thanks for the suggestion.
