### ISSUE TITLE
Evaluation on Columbia dataset

### ISSUE THREAD

**Issue by Claireikx** [joonson/syncnet_python#21]
Thank you very much for sharing the code and model of the paper. I have some questions about the testing methods used in this paper.
The frame rate of the Columbia video mentioned in the paper is 30fps. And both the public model and the paper were trained in 25fps.
1.Is the SyncNet model sensitive to the frame-rate? Should the frame rates of training and testing be consistent for model performance?
2. I wonder if you sampled the Columbia video to 25fps during the evaluation? 
Thank you for giving some details about this evaluation.

**Comment by joonson** [comment]
1. Yes,
2. Yes, the videos were resampled to 25fps.

**Comment by Claireikx** [comment]
Thank you for your reply.

**Comment by rockeyben** [comment]
If i have a 24fps dataset for testing only, what should I do ?
Some offsets may happen if I upsample frame rate to 25fps using ffmpeg, shall I just change all the fps parameter setting to 24?

**Comment by joonson** [comment]
You should resample the video to 25fps using ffmpeg, since this is what was done for non-25fps videos during training.
