### ISSUE TITLE
Is it possible for multiple face tracking?

### ISSUE THREAD

**Issue by someonefighting** [joonson/syncnet_python#27]
I notice that the function track_shot could track only one random face. What if I have multiple faces in a shot? Is it possible for multiple face tracking?

**Comment by joonson** [comment]
I believe the pipeline works for multiple faces in a shot. Have you tried running and visualizing the output?

**Comment by someonefighting** [comment]
The pipeline does works for multiple faces. And I notice that the pycrop file store all detected face tracks and its corresponding audios.
