### ISSUE TITLE
Error to download model

### ISSUE THREAD

**Issue by benjisympa** [joonson/syncnet_python#3]
Hi, thank you for your job.
I want to try your implementation but I get an ERROR 404 when I want to download the model :/
I also have a question, on which corpus the network was trained ?
Thanks

**Comment by joonson** [comment]
The script has been updated with the new address. Can you pull and try again?

**Comment by KeyKy** [comment]
@joonson wget http://www.robots.ox.ac.uk/~vgg/software/lipsync/data/face_detection_tf.zip 404 ERROR

**Comment by joonson** [comment]
It appears to be working fine -- maybe it was a temporary error.

**Comment by sdulyq** [comment]
I know the reason, you have to use new wget not the old one
