### ISSUE TITLE
The cropped face region

### ISSUE THREAD

**Issue by mycrazycracy** [joonson/syncnet_python#35]
Hi Joon,

Thanks for the excellent job. We are now using SyncNet to form a data collection pipeline. As I went through the code, I found that it detects the face region and then scale it before cropping. The default crop_scale=0.4, which means the cropped region is 1.4 times larger than the original face region. Is it the default behavior when training the model? Why should we do the scale since there should no information outside the real face. Any advice?

**Comment by joonson** [comment]
This is because the networks were trained on the LRS datasets, which were originally cropped to this specification. It will work best if the sizes of crops for testing are similar to training.

**Comment by mycrazycracy** [comment]
Thanks!

**Comment by mycrazycracy** [comment]
BTW, is LRS publicly accessible?
