### ISSUE TITLE
results not consistent with README.md

### ISSUE THREAD

**Issue by useafterfree** [joonson/syncnet_python#5]
OS: Ubuntu 16.04

requirements.txt:
`torch==0.4.0
numpy==1.14.3
scipy==1.0.1
opencv-python==3.4.0.14
python_speech_features==0.6
tensorflow==1.4
pyscenedetect==0.3.4`

Results:
`
AV offset: 	4 
Min dist: 	6.742
Confidence: 	10.447
`

Numbers are off, please advise

**Comment by joonson** [comment]
It appears that I didn't update the README when I updated the model. This has been fixed now.
