### ISSUE TITLE
how to remove temporal lags according to the offset?

### ISSUE THREAD

**Issue by windTwT** [joonson/syncnet_python#50]
Thanks for the work!
I wonder to know that after I get the offset between the audio and video, how can I do to  remove the temporal lags? That is, making the video synced with the audio?
Looking forward to your reply!

**Comment by monk-after-90s** [comment]
The same question

**Comment by joonson** [comment]
I think it is the same discussion as https://github.com/joonson/syncnet_python/issues/53
