### ISSUE TITLE
what mean this params: AV offset, Min dist, Confidence

### ISSUE THREAD

**Issue by hnsywangxin** [joonson/syncnet_python#65]
1:The unit of "offset" is milliseconds? Can you illustrate its meaning with an example?
2:Typically, the confidence range is from 0 to 1, but in this case, the range is different，when is it positive? when is it negative?

**Comment by piwawa** [comment]
Good question! It’s so dumb that the readme for this project doesn’t even have this basic explanation.

**Comment by SkylineYang** [comment]
AV offset: the offset between Audio and Video, -1 means the audio is faster than the video for 1 frame, +1 means the opposite;
Min dist: the minimal distance of "frames" between audio and video (I guess)
Confidence: how much confidence should we trust that audio and video are synchronized (I guess)

**Comment by hnsywangxin** [comment]
@SkylineYang 
thank you very much

**Comment by linqiu0-0** [comment]
AV offset:      3 
Min dist:       5.353
Confidence:     10.021

If the min dist means the minimal distance between audio and video, why is the AV offset smaller than the min dist in the example provided in the README.md? I thought the average should always be larger than the min dist.

**Comment by joonson** [comment]
> AV offset: the offset between Audio and Video, -1 means the audio is faster than the video for 1 frame, +1 means the opposite; Min dist: the minimal distance of "frames" between audio and video (I guess) Confidence: how much confidence should we trust that audio and video are synchronized (I guess)

AV offset: you are correct.

Min dist is the mean feature-wise distance between the audio and video at `AV offset`.
https://github.com/joonson/syncnet_python/blob/6efbb1c305c23f47a62b09cf4215a8ac45e97d49/SyncNetInstance.py#L132

Confidence is a score of how much closer the mean feature-wise distance is at the `AV offset` compared to other wrong offsets. Higher the confidence, more likely the sync offset is to be correct.
https://github.com/joonson/syncnet_python/blob/6efbb1c305c23f47a62b09cf4215a8ac45e97d49/SyncNetInstance.py#L135
