### ISSUE TITLE
what is ref

### ISSUE THREAD

**Issue by 523997931** [joonson/syncnet_python#67]
in the run_pipeline.py scripts, and others, I don't know what is the ref mean, I need another video as a reference? I try not set the param, but i don't get the offset txt, I don't know if it is beacause I don't set the ref

**Comment by piwawa** [comment]
Same question, I didn't even see this stupid file “$DATA_DIR/pywork/$REFERENCE/offsets.txt - audio-video offset values”

**Comment by joonson** [comment]
It just refers to video unique ID.
