### ISSUE TITLE
Full face or mouth region only 

### ISSUE THREAD

**Issue by ahmedelm** [joonson/syncnet_python#9]
Hi, 

Is the model uploaded here trained on the full faces, or just the mouth region ? 
The paper says that the network takes the mouth region as input, but the testing script takes in the full face. 

Thanks in advance

**Comment by joonson** [comment]
The model has been trained on the full faces, as in the example video.

**Comment by ahmedelm** [comment]
Many thanks for your response. 

What about the model in https://github.com/joonson/yousaidthat ? Is it trained on the face aswell, or the lips ?

**Comment by joonson** [comment]
It is also trained on the full face.
